# Exploratory data analysis

```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/setup.R"))
```

* Mapping out the underlying structure
* Identifying the most important variables
* Univariate visualizations

```{r}
kable(head(crime2003_2020 %>% count(`Incident Time`, name = "hour of the day") %>% arrange(desc(`hour of the day`))), "simple")
```

```{r}
kable(head(crime2003_2020 %>% count(`Incident Day of Week`, name = "day") %>% arrange(desc(day))), "simple")
```

```{r}
kable(head(crime2003_2020 %>% count(Resolution, name = "resolution") %>% arrange(desc(resolution))), "simple") 
```

```{r}
kable(head(crime2003_2020 %>% count(`Incident Category`, name = "category") %>% arrange(desc(category))), "simple")
```

```{r}
crime_number <- crime2003_2020  %>% arrange(`Incident Time`) %>%  arrange(`Incident Date`) %>%
  add_column(crime = 1) %>% select(crime, `Incident Date`)
#establish the number of crime from 2003 to 2017

crime_number_monhtly <- crime_number %>%
  mutate(month = month(`Incident Date`, label = TRUE),
         year  = year(`Incident Date`)) %>%
  group_by(year, month) %>%
  summarise(`Crime per Month` = sum(crime)) %>% mutate(`Month` = make_date(year, month)) %>%
  select(`Month`, `Crime per Month`)
#group the number of crime per month given the time period 2003 to 2017

library(ggthemes)
ggplot(crime_number_monhtly, aes(x = `Month`, y = `Crime per Month`)) +
  theme_economist_white() +
  scale_color_economist(name = "Seasons:") +
  geom_smooth(se = F)
```

```{r}
SFMAP <-
  leaflet() %>% addTiles() %>% #create a variable leaflet on which we add the map Tiles
  setView(-122.42, 37.78, zoom = 11) %>% # Precise the map target on San Francisco
  #add a marker for every point of the data set
  addProviderTiles(providers$MtbMap) %>%
  addProviderTiles(providers$Stamen.TonerLines,
                   options = providerTileOptions(opacity = 1)) %>%
  addProviderTiles(providers$Stamen.TonerLabels) #change the design of the map
```


* Multivariate visualizations
* Summary tables